export const SLOP_SIGNALS = [
  ["stock prose", "delve", /\b(?:delve(?:d|s)?|delving)\b/giu],
  ["stock prose", "pivotal", /\bpivotal\b/giu],
  ["stock prose", "tapestry", /\btapestr(?:y|ies)\b/giu],
  ["stock prose", "here's the thing", /\bhere(?:['’]s| is)\s+the\s+thing\b/giu],
  ["stock prose", "hope this helps", /\bhope\s+(?:this|that)\s+helps\b/giu],
  ["stock prose", "after careful consideration", /\bafter\s+careful\s+consideration\b/giu],
  ["stock prose", "quick update", /\bquick\s+update\b/giu],
  ["stock prose", "robust and reliable", /\brobust\s+and\s+reliable\b/giu],
  ["stock prose", "seamless", /\bseamless(?:ly)?\b/giu],
  ["stock prose", "important to note", /\b(?:it(?:['’]s| is)\s+)?important\s+to\s+note\b/giu],
  ["stock prose", "let me break this down", /\blet\s+me\s+break\s+(?:this|that|it)\s+down\b/giu],
  ["stock prose", "let's dive in", /\blet(?:['’]s| us)\s+dive\s+in\b/giu],
  ["stock prose", "let's unpack this", /\blet(?:['’]s| us)\s+unpack\s+(?:this|that|it)\b/giu],
  ["stock prose", "at its core", /\bat\s+its\s+core\b/giu],
  ["stock prose", "Certainly.", /^\s*certainly[.!]/gimu],
  ["stock prose", "I'd be happy to", /\bI(?:['’]d| would)\s+be\s+happy\s+to\b/giu],
  ["stock prose", "worth noting", /\bit(?:['’]s| is)\s+worth\s+noting\b/giu],
  ["stock prose", "in the realm of", /\bin\s+the\s+realm\s+of\b/giu],
  ["stock prose", "ever-evolving landscape", /\bever[-\s]+evolving\s+landscape\b/giu],
  ["stock prose", "game changer", /\bgame[-\s]+changer\b/giu],
  ["stock prose", "seamlessly integrates", /\bseamlessly\s+(?:integrat\w*|blend\w*)\b/giu],
  ["stock prose", "rich tapestry", /\b(?:rich|intricate)\s+tapestry\b/giu],
  ["stock prose", "at the end of the day", /\bat\s+the\s+end\s+of\s+the\s+day\b/giu],
  ["coding catchphrase", "load-bearing", /\bload[-\s]+bearing\b/giu],
  ["coding catchphrase", "honest take", /\bhonest\s+(?:take|evaluation|assessment)\b/giu],
  ["coding catchphrase", "precise mechanism", /\bprecise\s+mechanism\b/giu],
  ["coding catchphrase", "and that matters", /\band\s+that\s+matters\b/giu],
  ["coding catchphrase", "key insight", /\bkey\s+insight\b/giu],
  [
    "coding catchphrase",
    "without ceremony",
    /\b(?:without|with\s+no|needs?\s+no|requires?\s+no)\s+(?:additional\s+)?ceremony\b/giu,
  ],
  ["coding catchphrase", "earns its keep", /\bearn(?:s|ed|ing)?\s+(?:its|their|the)\s+keep\b/giu],
  [
    "coding catchphrase",
    "keeps things honest",
    /\bkeep(?:s|ing)?\s+(?:(?:things|us|this|that)|(?:the|our|your)\s+[\w-]+)\s+honest\b/giu,
  ],
  ["coding catchphrase", "belt and suspenders", /\bbelt[-\s]+and[-\s]+suspenders\b/giu],
  ["coding catchphrase", "soup to nuts", /\bsoup[-\s]+to[-\s]+nuts\b/giu],
  [
    "coding catchphrase",
    "architectural seam",
    /\b(?:clean|natural|architectural|integration)\s+seam\b/giu,
  ],
  [
    "excessive agreement",
    "absolutely right",
    /\byou(?:['’]re|\s+are)\s+(?:absolutely|completely|entirely)\s+right\b/giu,
  ],
  [
    "excessive agreement",
    "right to call that out",
    /\byou(?:['’]re|\s+are)\s+right\s+to\s+(?:call|point|flag)\s+(?:me|that|this)\s+out\b/giu,
  ],
  [
    "excessive agreement",
    "great question",
    /\b(?:great|excellent|fantastic)\s+(?:question|point|observation)\b/giu,
  ],
  ["excessive agreement", "real gap", /\b(?:a\s+)?real\s+gap\b/giu],
  ["excessive agreement", "error in my framing", /\berror\s+in\s+(?:my|the)\s+framing\b/giu],
  ["excessive agreement", "overcomplicated it", /\bI\s+overcomplicated\s+(?:it|this|that)\b/giu],
  ["excessive agreement", "genuinely", /\bgenuinely\b/giu],
  [
    "rhetorical template",
    "not X but Y",
    /\b(?:it(?:['’]s|\s+is)|this(?:\s+is|\s+isn['’]t)|that(?:\s+is|\s+isn['’]t))\s+(?:not\s+)?[^\n.!?]{1,100}[;,.—–]\s*(?:it(?:['’]s|\s+is)|this\s+is|but)\s+[^\n.!?]{1,100}/giu,
  ],
  ["rhetorical template", "bottom line", /\b(?:bottom\s+line|the\s+takeaway|in\s+short)\s*:/giu],
  [
    "rhetorical template",
    "mental model",
    /\b(?:the\s+)?(?:simplest|useful|right)\s+mental\s+model\b/giu,
  ],
  [
    "rhetorical template",
    "not just X but Y",
    /\bnot\s+just\s+[^\n.!?]{1,100},?\s+but\s+[^\n.!?]{1,100}/giu,
  ],
] as const;
