import type { WordEntry, Language, Severity, WordKind } from "../types.js";

function family(
  group: string,
  variants: string,
  severity: Severity,
  language: Language = "en",
  kind: WordKind = "swear",
  ambiguous: readonly string[] = [],
): WordEntry[] {
  return variants.split("|").map((word) => ({
    word,
    group,
    language,
    kind,
    severity,
    ...(ambiguous.includes(word) ? { ambiguous: true } : {}),
  }));
}
export const DEFAULT_WORDS: WordEntry[] = [
  ...family(
    "fuck",
    "fuck|fucking|fucked|fucker|fuckers|fuckin|fucks|motherfucker|motherfucking|motherfuckers|motherfucked|motherfuckin|mothafucka|mothafucker|mothafuckers|fuckup|fuckoff|clusterfuck|fuckwit|fuckface|fuckhead|dumbfuck|fuckwad|fuckwads|fukc|fukcing|fukced|fukcer|fcuk|fcuking|fcuked|fuk|fuking|fuked|fuker|fuxk|fuxking",
    "strong",
  ),
  ...family(
    "shit",
    "shit|shite|shitty|shitting|shits|shitted|shitter|shitters|shittier|shittiest|bullshit|horseshit|dipshit|shitshow|shithead|shitheads|shithole|shitface|shitfaced|shitstain|shitbag|apeshit|dumbshit|shitfuck|hsit|siht|shti|sjit|shjt|bulshit|bullsht",
    "strong",
  ),
  ...family("ass", "ass|asses|arse", "moderate"),
  ...family("ass", "asshole|assholes|arsehole|jackass|dumbass|asshat|asswipe", "strong"),
  ...family("ass", "fatass", "moderate"),
  ...family("ass", "badass", "mild"),
  ...family("damn", "damn|damned|damnit|dammit|goddamn|goddamnit|goddammit", "moderate"),
  ...family("bitch", "bitch|bitches|bitching|bitchy|bitchass", "strong"),
  ...family("bastard", "bastard|bastards", "strong"),
  ...family("piss", "piss|pissed|pissing|pissoff", "moderate"),
  ...family("dick", "dick", "moderate"),
  ...family("dick", "dickhead", "strong"),
  ...family("crap", "crap|crappy|crapping", "moderate"),
  ...family("hell", "hell", "mild"),
  ...family("wtf", "wtf", "mild"),
  ...family("stfu", "stfu", "mild"),
  ...family("lmao", "lmao|lmfao", "mild"),
  ...family("cunt", "cunt|cunts", "strong"),
  ...family("bollocks", "bollocks", "moderate"),
  ...family("bugger", "bugger", "moderate"),
  ...family("twat", "twat", "strong"),
  ...family("bellend", "bellend", "strong"),
  ...family("wanker", "wanker", "strong"),
  ...family("tosser", "tosser", "moderate"),
  ...family("cock", "cock|cocksucker", "strong"),
  ...family("prick", "prick", "moderate"),
  ...family("douche", "douche|douchebag", "moderate"),
  ...family("knobhead", "knobhead", "moderate"),
  ...family("sod", "sod off", "moderate"),
  ...family("bloody", "bloody", "mild"),
  ...family("ffs", "ffs", "mild"),
  ...family("fml", "fml", "mild"),
  ...family("af", "af", "mild", "en", "swear", ["af"]),
  ...family("slut", "slut", "strong"),
  ...family("whore", "whore", "strong"),
  ...family("pussy", "pussy", "moderate", "en", "swear", ["pussy"]),
  ...family("balls", "balls", "mild", "en", "swear", ["balls"]),
  ...family(
    "bewakoof",
    "bewakoof|bewaquf|bewakuf|bewakoofi|bewkoof|bewkuf|bevkoof|bevkuf|bevakoof",
    "mild",
    "hi",
    "insult",
  ),
  ...family("bakwas", "bakwas|bakwaas|bakwaasiyat", "mild", "hi", "insult"),
  ...family("saala", "saala|sala|saale|sale|saali|sali", "mild", "hi", "insult", [
    "sala",
    "sale",
    "sali",
  ]),
  ...family(
    "chutiya",
    "chutiya|chutia|chootiya|chutiye|chutiyeh|chutiyapa|chutiyap|chutiyapanti",
    "strong",
    "hi",
  ),
  ...family(
    "gandu",
    "gandu|gaandu|gandoo|gaand|gand|gaandfat|gaandmasti|gaandufad|gandfattu",
    "strong",
    "hi",
    "swear",
    ["gand"],
  ),
  ...family(
    "behenchod",
    "behenchod|bhenchod|bahenchod|bhenchodd|behenchodd|bhencho|pencho|behen chod|bc|b.c.",
    "strong",
    "hi",
    "swear",
    ["bc"],
  ),
  ...family(
    "madarchod",
    "madarchod|maderchod|madharchod|madar-chod|madarchoot|madarchut|machod|madar chod|mc|m.c.",
    "strong",
    "hi",
    "swear",
    ["mc"],
  ),
  ...family(
    "bhosdike",
    "bhosdike|bhosadike|bhosdiwale|bhosdi|bhosda|bhoshda|bhosad|bhosada|bhonsdike|bhosdiki|bhosdiwala|bhosadi ke|bsdk|b.s.d.k",
    "strong",
    "hi",
  ),
  ...family("bhasad", "bhasad", "moderate", "hi"),
  ...family(
    "lauda",
    "lauda|laude|loda|lode|lawda|lavda|lund|lundh|lodu|laudey|laura|lora|lulli|lulla|lun",
    "strong",
    "hi",
    "swear",
    ["laura", "lora"],
  ),
  ...family("bakchod", "bakchod|bakchodi", "strong", "hi"),
  ...family(
    "harami",
    "harami|haramzade|haramzada|haramjada|haraamjaada|haramzyada|haraamzyaada",
    "strong",
    "hi",
  ),
  ...family("haramkhor", "haramkhor|haraamkhor", "moderate", "hi"),
  ...family("kamina", "kamina|kamine|kaminey", "moderate", "hi", "insult"),
  ...family("bhadwa", "bhadwa|bhadwe|bhadwi|bhadve|bhadva|bhadvi|bhandve|bhadua", "strong", "hi"),
  ...family("jhaat", "jhaat|jhat|jhaatu|jhatu|jhant|jhantu", "strong", "hi"),
  ...family("choot", "choot|chut", "strong", "hi"),
  ...family("chutad", "chutad|chutadd|chuttad", "strong", "hi"),
  ...family("fuddi", "fudda|fuddi", "strong", "hi"),
  ...family(
    "chod",
    "chod|chodu|chudaap|chude|chud|chudai|chudai khanaa|chudam chudai|tu chuda",
    "strong",
    "hi",
    "swear",
    ["chud"],
  ),
  ...family("randi", "raand|randi|randaap|randi rona|rand", "strong", "hi", "swear", ["rand"]),
  ...family("tatti", "tatti", "moderate", "hi"),
  ...family("aand", "aand|tatte|gote", "moderate", "hi"),
  ...family("moot", "moot|mut|peshab|peshaab", "moderate", "hi", "swear", ["mut"]),
  ...family("chooche", "chooche|chuchi", "strong", "hi"),
  ...family("mutthal", "mutthal", "strong", "hi"),
  ...family("tharki", "tharak|tharki", "moderate", "hi", "insult"),
  ...family("kutta", "kutta|kutte|kuttiya", "moderate", "hi"),
  ...family("suar", "suar|suwar", "moderate", "hi"),
  ...family("gadha", "gadha", "mild", "hi", "insult"),
  ...family("fattu", "fattu", "mild", "hi", "insult"),
  ...family("ullu", "ullu", "mild", "hi", "insult"),
  ...family("bevda", "bevda|bewda", "mild", "hi", "insult"),
  ...family("charsi", "charsi", "mild", "hi", "insult"),
  ...family("dalal", "dalal", "mild", "hi", "insult"),
  ...[
    "please|pls|plz",
    "thank you|thanks|thankyou|ty|thx",
    "appreciate|appreciated|appreciates|appreciating",
  ].flatMap((words, index) =>
    words.split("|").map((word) => ({
      word,
      group: ["please", "thanks", "appreciate"][index],
      language: "en" as const,
      kind: "polite" as const,
    })),
  ),
  ...[
    "shukriya|shukria|shukriyaa",
    "dhanyavaad|dhanyavad|dhanyawad|dhanyawaad",
    "kripya|kripaya|kripa",
    "meherbani|mehrbani|meharbani",
  ].flatMap((words) =>
    words.split("|").map((word) => ({
      word,
      group: words.split("|")[0],
      language: "hi" as const,
      kind: "polite" as const,
    })),
  ),
];
