export const TERMINAL = {
  width: 78,
  minimumWidth: 42,
  maximumWidth: 100,
  barWidth: 18,
  wordWidth: 18,
  calendar: {
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    cellWidth: 2,
    missing: "·",
    zero: "□",
    levels: ["░", "▒", "▓", "█"],
    tones: ["calendarLow", "calendarMedium", "calendarHigh", "calendarPeak"],
  },
  controls: { clearScreen: "\u001b[H\u001b[2J" },
  tierColors: ["green", "green", "yellow", "yellow", "red", "red"],
  frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"],
  colors: {
    reset: "\u001b[0m",
    bold: "\u001b[1m",
    dim: "\u001b[2m",
    orange: "\u001b[38;5;208m",
    red: "\u001b[91m",
    green: "\u001b[92m",
    yellow: "\u001b[93m",
    blue: "\u001b[94m",
    cyan: "\u001b[96m",
    magenta: "\u001b[95m",
    gray: "\u001b[90m",
    white: "\u001b[97m",
    calendarLow: "\u001b[38;5;22m",
    calendarMedium: "\u001b[38;5;28m",
    calendarHigh: "\u001b[38;5;34m",
    calendarPeak: "\u001b[38;5;40m",
  },
  commands: {
    scan: "LANGUAGE SCAN",
    cost: "TOKEN COSTS",
    slop: "ASSISTANT PATTERNS",
    report: "FULL REPORT",
    doctor: "HISTORY CHECK",
  },
} as const;
